const ReactQueryKeys = {
  CREATE_PROFILE: 'CREATE_PROFILE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_REMINDERS: 'GET_REMINDERS',
  GET_MEDICATION_HISTORY: 'GET_MEDICATION_HISTORY',
};

export default ReactQueryKeys;
